pipeline:
  name: git_pipeline
  identifier: git_pipeline
  template:
    templateRef: git_template
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: deploy
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: CustomDeployment
                    spec:
                      artifacts:
                        primary:
                          type: DockerRegistry
                          spec:
                            tag: <+input>
              environment:
                infrastructureDefinitions:
                  - identifier: TEST
                    inputs:
                      identifier: TEST
                      type: CustomDeployment
                      spec:
                        variables:
                          - name: gcp
                            type: Connector
                            value: <+input>
                          - name: gitlab
                            type: Connector
                            value: <+input>
  tags: {}
  projectIdentifier: rishabhtest
  orgIdentifier: deafult
